export const mockPostData = [
  {
    id: 1,
    userName: '제주도 정착 꿈나무',
    title: '제주시분들 이주민 반기나요?',
    contents:
      '이번에 제주시 쪽으로 이사갈까 하는데 제가 정이 많은 편인데 걱정이 되어서 글을 올립니다. 혹시 거주민이신 분들 정보 제공 가능하신가요? 감사합니다.',
    createdAt: '2022-08-24 4:44',
    commentsCount: 1,
    category: '부동산',
    location: '서귀포시',
    comments: [
      {
        id: 1,
        userName: '제주도 정착 꿈나무',
        contents: '글쓴이다',
        createAt: '2022-08-24 4:44',
      },
      {
        id: 2,
        userName: '제주도 정착 꿈나무',
        contents: '글쓴이가 맞다',
        createAt: '2022-08-24 14:44',
      },
      {
        id: 3,
        userName: '제주사랑',
        contents: '난 글쓴이가 아냐',
        createAt: '2022-08-24 4:54',
      },
    ],
    years: 0,
  },
  {
    id: 2,
    userName: '제주사랑',
    title: '서귀포에서 창업하려고하는데',
    contents: '잠재 고객을 찾습니다.',
    createdAt: '2022-08-25 4:44',
    commentsCount: 2,
    years: 5,
    category: '카페',
    location: '서귀포시',
    comments: [
      {
        id: 4,
        userName: '제주도 정착 꿈나무',
        contents: '글쓴이가 맞다X',
        createAt: '2022-08-24 4:44',
      },
      {
        id: 5,
        userName: '제주도 정착 꿈나무',
        contents: '난 글쓴이가 아냐',
        createAt: '2022-08-24 14:44',
      },
      {
        id: 6,
        userName: '제주사랑',
        contents: '글쓴이가 맞다',
        createAt: '2022-08-24 4:54',
      },
    ],
  },
  {
    id: 3,
    userName: '제주도 정착 꿈나무',
    title: '제주 맛집 정보좀..',
    contents:
      '이번에 제주시 쪽으로 이사갈까 하는데 제가 정이 많은 편인데 걱정이 되어서 글을 올립니다. 혹시 거주민이신 분들 정보 제공 가능하신가요? 감사합니다.',
    createdAt: '2022-08-25 11:23',
    commentsCount: 1,
    years: 1,
    category: '여가활동',
    location: '제주시',
    comments: [
      {
        id: 4,
        userName: '제주도 정착 꿈나무',
        contents: '글쓴이가 맞다X',
        createAt: '2022-08-24 4:44',
      },
      {
        id: 5,
        userName: '제주도 정착 꿈나무',
        contents: '난 글쓴이가 아냐',
        createAt: '2022-08-24 14:44',
      },
      {
        id: 6,
        userName: '제주사랑',
        contents: '글쓴이가 맞다',
        createAt: '2022-08-24 4:54',
      },
    ],
  },
  {
    id: 4,
    userName: '제주사랑',
    title: '서귀포에서 창업하려고하는데',
    contents: '잠재 고객을 찾습니다.',
    createdAt: '2022-08-24 4:44',
    commentsCount: 2,
    years: 0,
    category: '인구',
    location: '제주시',
    comments: [
      {
        id: 7,
        userName: '제주도 정착 꿈나무',
        contents: '글쓴이가 맞다X',
        createAt: '2022-08-24 4:44',
      },
      {
        id: 8,
        userName: '제주도 정착 꿈나무',
        contents: '난 글쓴이가 아냐',
        createAt: '2022-08-24 14:44',
      },
      {
        id: 9,
        userName: '제주사랑',
        contents: '글쓴이가 맞다',
        createAt: '2022-08-24 4:54',
      },
    ],
  },
  {
    id: 5,
    userName: '제주도 정착 꿈나무',
    title: '제주시분들 이주민 반기나요?',
    contents:
      '이번에 제주시 쪽으로 이사갈까 하는데 제가 정이 많은 편인데 걱정이 되어서 글을 올립니다. 혹시 거주민이신 분들 정보 제공 가능하신가요? 감사합니다.',
    createdAt: '2022-08-24 4:44',
    commentsCount: 1,
    years: 0,
    category: '맛집',
    location: '제주시',
    comments: [
      {
        id: 10,
        userName: '제주도 정착 꿈나무',
        contents: '글쓴이가 맞다X',
        createAt: '2022-08-24 4:44',
      },
      {
        id: 11,
        userName: '제주도 정착 꿈나무',
        contents: '난 글쓴이가 아냐',
        createAt: '2022-08-24 14:44',
      },
      {
        id: 12,
        userName: '제주사랑',
        contents: '글쓴이가 맞다',
        createAt: '2022-08-24 4:54',
      },
    ],
  },
  {
    id: 6,
    userName: '제주사랑',
    title: '서귀포에서 창업하려고하는데',
    contents: '잠재 고객을 찾습니다.',
    createdAt: '2022-08-24 4:44',
    commentsCount: 2,
    years: 0,
    category: '카페',
    location: '서귀포시',
    comments: [
      {
        id: 13,
        userName: '제주도 정착 꿈나무',
        contents: '글쓴이가 맞다X',
        createAt: '2022-08-24 4:44',
      },
      {
        id: 14,
        userName: '제주도 정착 꿈나무',
        contents: '난 글쓴이가 아냐',
        createAt: '2022-08-24 14:44',
      },
      {
        id: 15,
        userName: '제주사랑',
        contents: '글쓴이가 맞다',
        createAt: '2022-08-24 4:54',
      },
    ],
  },
];
